version: '3.9'

services:

  server:
    image: postgrest/postgrest:v8.0.0
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://sample_user:sample_password@db:5432/sample_db
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: sample_user
      PGRST_SERVER_PROXY_URI: "http://127.0.0.1:3000"
    depends_on:
      - db
  
  db:
    image: postgres:13.3-alpine
    restart: always
    ports:
      - "9000:5432"
    environment:
      POSTGRES_DB: sample_db
      POSTGRES_USER: sample_user
      POSTGRES_PASSWORD: sample_password
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
